Repository chipsalliance/f4pga-examples, pull requests merged in 2022-08, with the labels that each got.

#338 Fix inconsistency between QuickLogic and xc7 packages
  .github/scripts/build-examples.sh
  .github/scripts/install-toolchain.sh
  docs/building-examples.rst
  docs/getting.rst
  eos-s3/btn_counter/dummy.sdc
  eos-s3/environment.yml
  eos-s3/requirements.txt
  xc7/requirements.txt
Labels: documentation, enhancement

#348 eos-s3: btn_counter: use F4PGA build flow by default
  eos-s3/btn_counter/Makefile
  eos-s3/btn_counter/flow.json
Labels: enhancement

#351 eos-s3/btn_counter/Makefile: dump jlink,openocd,header,binary
  common/requirements.txt
  docs/building-examples.rst
  eos-s3/btn_counter/Makefile
  eos-s3/btn_counter/README.rst
Labels: enhancement, merge-if-green

#353 docs: do not use 'install' subdir
  .github/latest.patch
  common/requirements.txt
  docs/building-examples.rst
  docs/getting.rst
  eos-s3/btn_counter/Makefile
Labels: enhancement, merge-if-green

#354 docs: 'understanding' moved to f4pga
  docs/customizing-makefiles.rst
  docs/development/running-ci-locally.rst
  docs/index.rst
  docs/personal-designs.rst
  docs/project-f.rst
  docs/understanding.rst
Labels: documentation, enhancement, merge-if-green

#355 docs/getting: use tabs to export F4PGA_PACKAGES
  .github/latest.patch
  .github/scripts/install-toolchain.sh
  docs/getting.rst
Labels: documentation, enhancement, merge-if-green

#356 docs/customizing-makefiles: add label
  docs/customizing-makefiles.rst
Labels: documentation, enhancement

#357 docs/getting: guidelines to bump the yosys plugin moved to conda-eda
  docs/getting.rst
Labels: documentation, enhancement

#359 common/requirements: bump f4pga
  .github/latest.patch
  common/requirements.txt
  docs/getting.rst
  xc7/counter_test/Makefile
Labels: enhancement, merge-if-green
